### ISSUE TITLE
socket.io.js and hollywood.js are missing

### ISSUE THREAD

**Issue by joseyukio** [amirrajan/word-finder#4]
Hi,
this project works fine but there are 2 GET request for:
socket.io/socket.io.js
public/hollywood.js
that are responded with 404.
![image](https://cloud.githubusercontent.com/assets/11370071/6576264/a1a6b162-c714-11e4-95dc-e4423013ee4f.png)

I checked the installation of word-finder and those files do not exist.
Could you check it out if those files are still needed or if the reference to them should be removed?

BR,
Yukio

**Comment by amirrajan** [comment]
Holy crap, sorry for the late reply. They aren't needed in this application. I'll remove them.

**Comment by amirrajan** [comment]
Fixed
