### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by guptaaditya** [amirrajan/word-finder#5]
I followed instructions to install word-finder locally. After cloning on first jasmine-node . test command, it says underscore missing, error: MODULE_NOT_FOUND

I dont know how to fix this error. absolutely new to node-js

**Comment by amirrajan** [comment]
ah! sorry for that.

Try `npm install -g underscore` and see if that works.

**Comment by guptaaditya** [comment]
Thank you. This is very helpful as getting started. I learnt installing modules at the least with the exception. 
Hope the app takes me long way.

**Comment by amirrajan** [comment]
excellent! be sure to try all the other examples too: http://amirrajan.net/nodejs-by-example/
